# Generated by Django 3.1.1 on 2021-10-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_number',
            field=models.CharField(default=1, max_length=100, verbose_name='Legal Number(CNPJ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name(Nome)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
