# Generated by Django 3.1.1 on 2021-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211027_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='imagens', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
